/*
 * sim_audio.h — ES8311 audio codec driver for SimCoupe (Olimex ESP32-P4-PC)
 *
 * Hardware (Olimex ESP32-P4-PC Rev B):
 *   I2C1  SDA=GPIO7  SCL=GPIO8  (400 kHz, shared with LT8912B display bridge)
 *   ES8311 I2C address: 0x18 (CE/AD0=GND)
 *   GPIO6 = CODEC_PWR_DIS# (active LOW — drive LOW to power on codec)
 *
 *   I2S1:
 *     DOUT (ESP→codec DAC): GPIO9  (I2S_DSDIN)
 *     WS   (LRCK):          GPIO10 (I2S_LRCK)
 *     DIN  (codec ADC→ESP): GPIO11 (I2S_ASDOUT)
 *     BCLK:                 GPIO12 (I2S_SCLK)
 *     MCLK:                 GPIO13 (I2S_MCLK)
 *
 * Audio format: 44100 Hz, stereo, 16-bit signed PCM
 * MCLK = 256 × 44100 = 11,289,600 Hz  (generated by I2S APLL)
 * ESP32-P4 is I2S master; ES8311 is slave.
 *
 * API:
 *   sim_audio_init()              — initialize I2C + ES8311 + I2S (creates own I2C bus)
 *   sim_audio_init_with_bus()     — initialize using existing I2C bus (shared with display)
 *   sim_audio_write()             — write stereo PCM samples (int16_t L/R interleaved)
 *   sim_audio_set_volume()        — set output volume 0-100
 *   sim_audio_get_tx_handle()     — get I2S TX channel handle
 *   sim_audio_get_i2c_bus()       — get I2C bus handle (for sharing with sim_display)
 *   sim_audio_deinit()            — release resources
 */

#pragma once

#include <stdint.h>
#include <stddef.h>
#include "esp_err.h"
#include "driver/i2s_std.h"
#include "driver/i2c_master.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Initialize the ES8311 codec and I2S interface.
 *
 * Creates a new I2C master bus, powers on the codec (GPIO6 active LOW),
 * configures the ES8311 for 44100 Hz stereo 16-bit output, and starts
 * I2S with APLL.
 *
 * @return ESP_OK on success, or an esp_err_t on failure.
 */
esp_err_t sim_audio_init(void);

/**
 * @brief Initialize the ES8311 codec using an existing I2C bus handle.
 *
 * Same as sim_audio_init() but skips creating a new I2C master bus.
 * Use this when sim_display already owns the I2C bus on the same port.
 *
 * @param  bus  Existing I2C master bus handle to use. Must remain valid
 *              for the lifetime of the audio driver.
 * @return ESP_OK on success, or an esp_err_t on failure.
 */
esp_err_t sim_audio_init_with_bus(i2c_master_bus_handle_t bus);

/**
 * @brief Write stereo PCM audio samples to the DAC output.
 *
 * Sends stereo 16-bit signed PCM samples to the ES8311 DAC via I2S DMA.
 * SimCoupe generates native stereo output — samples are L/R interleaved int16_t.
 * num_samples is the total count of int16_t values (2 per stereo frame).
 *
 * @param  samples     Pointer to int16_t sample buffer (L, R, L, R, ...)
 * @param  num_samples Number of int16_t samples (not frames, not bytes)
 * @param  timeout_ms  Timeout in milliseconds (portMAX_DELAY = wait forever)
 * @return Number of samples actually written, or -1 on error.
 */
int sim_audio_write(const int16_t *samples, size_t num_samples, uint32_t timeout_ms);

/**
 * @brief Set the ES8311 DAC output volume.
 *
 * @param  volume  Volume level 0 (mute) to 100 (maximum)
 * @return ESP_OK on success.
 */
esp_err_t sim_audio_set_volume(int volume);

/**
 * @brief Get the I2S TX channel handle (for advanced use).
 *
 * @return I2S TX channel handle, or NULL if not initialized.
 */
i2s_chan_handle_t sim_audio_get_tx_handle(void);

/**
 * @brief Get the I2C bus handle (so sim_display can share the bus).
 *
 * @return I2C master bus handle, or NULL if not initialized.
 */
i2c_master_bus_handle_t sim_audio_get_i2c_bus(void);

/**
 * @brief De-initialize and release all audio resources.
 */
void sim_audio_deinit(void);

#ifdef __cplusplus
}
#endif
