/* config.h — Manual replacement for CMake-generated config.h
 *
 * Generated by CMake on a normal build from config.h.in.
 * For the ESP32-P4 port we set these manually.
 */

#pragma once

/* SimCoupe version */
#define SIMCOUPE_MAJOR_VERSION  1
#define SIMCOUPE_MINOR_VERSION  2
#define SIMCOUPE_PATCH_VERSION  0

/* zlib — not available on ESP32 */
/* #undef HAVE_LIBZ */

/* bzip2 — not available on ESP32 */
/* #undef HAVE_LIBBZ2 */

/* SDL2 — not used on ESP32 */
/* #undef HAVE_LIBSDL2 */

/* OpenGL — not available on ESP32 */
/* #undef HAVE_OPENGL */

/* XAudio2 — Windows only */
/* #undef HAVE_XAUDIO2REDIST */

/* std::filesystem — ESP-IDF toolchain (GCC 13) does have it,
 * but ghc::filesystem is safer and already vendored. */
/* #undef HAVE_STD_FILESYSTEM */

/* Resource directory — SD card mount point */
#define RESOURCE_DIR "/sdcard"
